# Generated by Django 4.2.3 on 2023-08-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_featurednews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedNews',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
    ]
